dist: xenial
language: python
python:
  - "3.8"
# command to install dependencies

addons:
  sonarcloud:
    organization: "jacques15" # the key of the org you chose at step #3
    
install:
  - pip install -U pytest
  - pip install -U flask
  - pip install -U azure-cognitiveservices-search-customsearch
  - nvm install 10
# command to run tests
script:
  - sonar-scanner
  - pytest
  #- python3 Website_python.py
  
deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: Web_APP
  env: Webapp-env
  bucket_name: elasticbeanstalk-us-east-1-523448548376
  bucket_path: Web_APP
  #on: 
    #branch: master
  
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
