language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.9-dev"  # 3.9 development branch
  - "nightly"  # nightly build
# command to install dependencies
install:
  - pip install -U pytest
  - pip install -U flask
  - pip install -U azure-cognitiveservices-search-customsearch
# command to run tests
script:
  - pytest
  - python3 Website_python.py
