language: python
python:
  - "3.9"
# command to install dependencies
install:
  - pip install -U pytest
  - pip install -U flask
  - pip install -U azure-cognitiveservices-search-customsearch
# command to run tests
script:
  - pytest
  - python3 Website_python.py
